# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{scriptty}
  s.version = "1.3.0"
  s.platform = %q{java}

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dwayne Litzenberger"]
  s.date = %q{2010-12-07}
  s.description = %q{ScripTTY is a JRuby application and library that lets you control full-screen
terminal applications using an expect-like scripting language and a full-screen
matching engine.
}
  s.email = %q{dlitz@infonium.ca}
  s.executables = ["scriptty-dump-screens", "scriptty-capture", "scriptty-transcript-parse", "scriptty-replay", "scriptty-term-test"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitattributes",
    "COPYING",
    "COPYING.LESSER",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/scriptty-capture",
    "bin/scriptty-dump-screens",
    "bin/scriptty-replay",
    "bin/scriptty-term-test",
    "bin/scriptty-transcript-parse",
    "examples/captures/xterm-overlong-line-prompt.bin",
    "examples/captures/xterm-vim-session.bin",
    "examples/demo-capture.rb",
    "examples/demo-telnet-session-screens.txt",
    "examples/demo-telnet-session.rb",
    "examples/rdispatch/demo-request-dispatcher.rb",
    "examples/rdispatch/done_screen.txt",
    "examples/rdispatch/login.rb",
    "examples/rdispatch/start_screen.txt",
    "examples/rdispatch/vim_screen.txt",
    "examples/telnet-nego.rb",
    "lib/scriptty/apps/capture_app.rb",
    "lib/scriptty/apps/dump_screens_app.rb",
    "lib/scriptty/apps/replay_app.rb",
    "lib/scriptty/apps/term_test_app.rb",
    "lib/scriptty/apps/transcript_parse_app.rb",
    "lib/scriptty/cursor.rb",
    "lib/scriptty/exception.rb",
    "lib/scriptty/expect.rb",
    "lib/scriptty/multiline_buffer.rb",
    "lib/scriptty/net/console.rb",
    "lib/scriptty/net/event_loop.rb",
    "lib/scriptty/net/password_prompt.rb",
    "lib/scriptty/request_dispatcher.rb",
    "lib/scriptty/screen_pattern.rb",
    "lib/scriptty/screen_pattern/generator.rb",
    "lib/scriptty/screen_pattern/parser.rb",
    "lib/scriptty/term.rb",
    "lib/scriptty/term/dg410.rb",
    "lib/scriptty/term/dg410/dg410-client-escapes.txt",
    "lib/scriptty/term/dg410/dg410-escapes.txt",
    "lib/scriptty/term/dg410/parser.rb",
    "lib/scriptty/term/xterm.rb",
    "lib/scriptty/term/xterm/xterm-escapes.txt",
    "lib/scriptty/util/fsm.rb",
    "lib/scriptty/util/fsm/definition_parser.rb",
    "lib/scriptty/util/fsm/scriptty_fsm_definition.treetop",
    "lib/scriptty/util/transcript/reader.rb",
    "lib/scriptty/util/transcript/writer.rb",
    "test.watchr",
    "test/apps/capture_app_test.rb",
    "test/apps/transcript_parse_app_test.rb",
    "test/cursor_test.rb",
    "test/expect/screens.txt",
    "test/expect_test.rb",
    "test/fsm_definition_parser_test.rb",
    "test/fsm_test.rb",
    "test/multiline_buffer_test.rb",
    "test/net/event_loop_test.rb",
    "test/request_dispatcher_test.rb",
    "test/screen_pattern/generator_test.rb",
    "test/screen_pattern/parser_test.rb",
    "test/screen_pattern/parser_test/explicit_cursor_pattern.txt",
    "test/screen_pattern/parser_test/explicit_fields.txt",
    "test/screen_pattern/parser_test/multiple_patterns.txt",
    "test/screen_pattern/parser_test/simple_pattern.txt",
    "test/screen_pattern/parser_test/truncated_heredoc.txt",
    "test/screen_pattern/parser_test/utf16bebom_pattern.bin",
    "test/screen_pattern/parser_test/utf16lebom_pattern.bin",
    "test/screen_pattern/parser_test/utf8_pattern.bin",
    "test/screen_pattern/parser_test/utf8_unix_pattern.bin",
    "test/screen_pattern/parser_test/utf8bom_pattern.bin",
    "test/term/dg410/parser_test.rb",
    "test/term/xterm_test.rb",
    "test/test_helper.rb",
    "test/util/transcript/reader_test.rb",
    "test/util/transcript/writer_test.rb"
  ]
  s.homepage = %q{http://github.com/infonium/scriptty}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{write expect-like script to control full-screen terminal-based applications}
  s.test_files = [
    "examples/demo-capture.rb",
    "examples/demo-telnet-session.rb",
    "examples/rdispatch/demo-request-dispatcher.rb",
    "examples/rdispatch/login.rb",
    "examples/telnet-nego.rb",
    "test/apps/capture_app_test.rb",
    "test/apps/transcript_parse_app_test.rb",
    "test/cursor_test.rb",
    "test/expect_test.rb",
    "test/fsm_definition_parser_test.rb",
    "test/fsm_test.rb",
    "test/multiline_buffer_test.rb",
    "test/net/event_loop_test.rb",
    "test/request_dispatcher_test.rb",
    "test/screen_pattern/generator_test.rb",
    "test/screen_pattern/parser_test.rb",
    "test/term/dg410/parser_test.rb",
    "test/term/xterm_test.rb",
    "test/test_helper.rb",
    "test/util/transcript/reader_test.rb",
    "test/util/transcript/writer_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<treetop>, [">= 0"])
      s.add_runtime_dependency(%q<multibyte>, [">= 0"])
    else
      s.add_dependency(%q<treetop>, [">= 0"])
      s.add_dependency(%q<multibyte>, [">= 0"])
    end
  else
    s.add_dependency(%q<treetop>, [">= 0"])
    s.add_dependency(%q<multibyte>, [">= 0"])
  end
end

